language: java
jdk:
  - oraclejdk8
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx1024m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
branches:
  only:
    - master
install:
  - true
script:
  - ./gradlew check --stacktrace
